- name: Preparing environment
  include_tasks:
    file: "common/pre_install.yml"

- name: Installing requirements
  include_tasks:
    file: "{{ target_platform }}/install_dependencies.yml"

- name: Installing ModSecurity
  include_tasks:
    file: "common/install_mod_security.yml"

- name: Installing ModSecurity nginx connector
  include_tasks:
    file: "common/install_mod_security_nginx_connector.yml"

- name: Installing ModeSecurity community rules
  include_tasks:
    file: "common/install_community_rules.yml"

- name: Cleaning environment
  include_tasks:
    file: "common/post_install.yml"
