galaxy_info:
  author: Hasni Mehdi
  description: Nginx installer
  company: Black Cockpit
  license: MIT
  min_ansible_version: 2.1

  platforms:
  - name: Ubuntu
    versions:
    - all

  galaxy_tags:
  - nginx
  - web_server
dependencies: []
