- name: Deleting source directory
  file:
    path: "{{ source_dir }}"
    state: absent
    force: yes

- name: Creating tmp source directory
  file:
    path: "{{ source_dir }}"
    state: directory
    force: yes